# Generated by Django 4.0.6 on 2022-08-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0003_expense_type_income_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='type',
            field=models.CharField(default='Expense', max_length=7),
        ),
        migrations.AlterField(
            model_name='income',
            name='type',
            field=models.CharField(default='Income', max_length=6),
        ),
    ]
