# Generated by Django 4.0.6 on 2022-08-31 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExpenseApp', '0004_alter_expense_type_alter_income_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='type',
        ),
    ]
